### ISSUE TITLE
Support By-pass URL

### ISSUE THREAD

**Issue by thiner** [IvanJosipovic/OIDC-Guard#125]
The OIDC-Guard is amazing to enable jwt verification for ingress. It's working perfectly. However, I think it is very important to add a feature that allow by-pass URI or suffix. E.g. static files for web application should not be protected by jwt.

**Comment by IvanJosipovic** [comment]
Hey, check out this feature, https://github.com/IvanJosipovic/OIDC-Guard/wiki/Endpoints#skip-auth
Let me know if that works for you.
