### ISSUE TITLE
oidc-guard fails to start on Apple Silicon M1

### ISSUE THREAD

**Issue by Dariusch** [IvanJosipovic/OIDC-Guard#130]
Hello, I wanted to test OIDC-Guard locally on my docker-desktop cluster via helm.

I ran into the following error, emitted by the Pod logs:

```shell
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
```

Any idea what is going on and how to mitigate this?

**Comment by IvanJosipovic** [comment]
See this issue, https://github.com/docker/roadmap/issues/384
