### ISSUE TITLE
Does any guys run into the issue that always return 400 for the requests with the Content-Type `multipart/form-data`?

### ISSUE THREAD

**Issue by NoodlesWang2024** [IvanJosipovic/OIDC-Guard#268]

**Comment by IvanJosipovic** [comment]
I have not faced this issue. If you are able to reproduce the issue, it would be helpful if you can capture the original request and share it with me.

**Comment by IvanJosipovic** [comment]
Please reopen the issue if you are able help me to reproduce the problem.
