### ISSUE TITLE
Inject JSON claims as headers

### ISSUE THREAD

**Issue by gfrankliu** [IvanJosipovic/OIDC-Guard#33]
Google IAP can embedded additional information in the jwt header. If I need to inject a header from the claim nested in gcip.sign_in_attributes.group from [this example](https://cloud.google.com/iap/docs/signed-headers-howto#controlling_access_with_sign_in_attributes), how do I do it? Can we do flexible things using [JMESPath](https://jmespath.org/examples.html) to get what we want from the jwt?

**Comment by IvanJosipovic** [comment]
Can you show me the output of /userinfo?

**Comment by gfrankliu** [comment]
/userinfo returns the same json like [this](https://cloud.google.com/iap/docs/signed-headers-howto#controlling_access_with_sign_in_attributes).

**Comment by IvanJosipovic** [comment]
Interesting, so the library treads gcip as an embedded json string. This makes sense as the JWT is meant to be a key value pair.

Let me ponder about this, for now, can you can inject gcip and parse the json in your app?

**Comment by gfrankliu** [comment]
I have beautified it, /userinfo actually returns the gcip value is one escaped long string:

```
"gcip":"{\"auth_time\":1553219869,\"email\":\"demo_user@gmail.com\",...\"}"

```

I can inject gcip, and the backend receives this one long escaped string. It's a third party backend application that only understands a header that has the "role" information (came from the JWT gcip.firebase.sign_in_attributes.role). The only customization backend supports is the header name.

**Comment by IvanJosipovic** [comment]
This feature is available in 2.2.0 :)

https://github.com/IvanJosipovic/OIDC-Guard/wiki/Endpoints#inject-json-claims

**Comment by gfrankliu** [comment]
Thanks and I will give it a try later.
In the wiki example `inject-json-claim=role,gcim,$.firebase.sign_in_attributes.role`. Is "gcim" a typo? should be gcip matching what's in the jwt.

**Comment by IvanJosipovic** [comment]
That was a typo, its fixed now, thanks!

**Comment by gfrankliu** [comment]
ingress nginx was failing until I escape the $, then all works. Thanks!

`inject-json-claim=role,gcim,%24.firebase.sign_in_attributes.role`

**Comment by gfrankliu** [comment]
One thing I noticed is if the node is an array with multiple entries, eg:
```
"role": ["role1", "role2"]
```
Only the first entry "role1" is returned, instead of the list. It may not be a big deal since most of our users have single role, but I thought I would report here and see if we can return `role1,role2` in the response.

**Comment by IvanJosipovic** [comment]
It should respond with 2 headers,
role: role1
role: role2

See test, https://github.com/IvanJosipovic/OIDC-Guard/blob/2b22f4ea080111246936238c81e319b48d459cb3/tests/oidc-guard-tests/AuthTests.cs#L309

**Comment by gfrankliu** [comment]
Hm, maybe the nginx `nginx.ingress.kubernetes.io/auth-response-headers` has a bug that ignores the duplicated header names instead of combining values into a comma separated list. My backend behind nginx only received first one.

**Comment by IvanJosipovic** [comment]
v2.2.1 will be released shortly.

https://github.com/IvanJosipovic/OIDC-Guard/pull/36

**Comment by gfrankliu** [comment]
Works now!
